return {
	-- "nvim-neorg/neorg",
	-- lazy = true, -- Disable lazy loading as some `lazy.nvim` distributions set `lazy = true` by default
	-- version = "*", -- Pin Neorg to the latest stable release
	-- config = function()
	-- 	require("neorg").setup {
	-- 		load = {
	-- 			["core.defaults"] = {},
	-- 			["core.summary"] = {},
	-- 			["core.concealer"] = {
	-- 				icon_preset = "diamond"
	-- 			},
	-- 			["core.dirman"] = {
	-- 				config = {
	-- 					workspaces = {
	-- 						wiki = "~/wiki",
	-- 					},
	-- 					default_workspace = "wiki",
	-- 				},
	-- 			},
	-- 		},
	-- 	}
	-- end,
}
